### PR TITLE
chore: update readme.md

### PR DESCRIPTION
**Pull request by oates**
updated emoji

### CODE REVIEW

**Comment by zachariahmiller** [comment]
The commitlint job is broken we've been having to go fix it by pinning the version across different repos

**Review by zachariahmiller — APPROVED** [review]
🚀

**Comment by oates** [comment]
No it's 🏭

**Comment by zachariahmiller** [comment]
> No it's 🏭

the 🚀 was regarding your developer career, not which emoji you updated in your PR.

**Pull request merged**
